config/routes.rb
Rails.application.routes.draw do

  root 'home_page#index'

  namespace :admin do
    get 'home_page/index'
    get 'login'=>'home_page#login' #这个路由页面css效果有问题(原因不知道),目前使用下面的login路由
    get 'home_page/login'
  end

  post 'session/create'
  get 'session/destroy' ,as:'log_out'

  concern :freezingable do  #可继承此概念的路由
    patch :unfreezing, on: :member
    patch :freezing, on: :member
  end

  resources :teachers , concerns: [:freezingable] do
  end

  resources :text_books

  resources :test_papers do    #考试套题包含套题的section
    resources :sections
  end

  resources :subjects

  resources :employees , concerns: [:freezingable]

  resources :users do
    get :set_password , on: :member
  end

  get 'home_page/course_list' =>'home_page#course_list',as:'courseList'
  get 'home_page/lecturer_profile' => 'home_page#lecturer_profile', as:'lecturer_profile'
  get 'home_page/lecturer_list' => 'home_page#lecturer_list', as:'lecturers_intro'

  resources :articles do
    get 'tags/:tag', to: 'articles#index', as: :tag ,on: :collection
  end

  get 'home_page/search'
  get 'home_page/upload'
  get 'home_page/training_class_schedule'
  get 'home_page/delete_schedule'
  post 'home_page/upload'

  get 'home_page/index'
  get 'home_page/reports'
  get 'home_page/big_data_report_scores'
  post 'home_page/big_data_report_scores'

  resources :questions

  resources :students , concerns: [:freezingable] do
    get :search_with_trainingclass,on: :collection # 带培训班id 的学员查询,会从查询结果中过滤掉培训班中已有的学员( 培训班 Set_Students 页面专用)
    get :search , on: :collection

    resources :real_scores do
      get :index_with_all_examinations ,on: :collection #列出某个学员的 所有真实考试成绩 (统计报表)(真实考试成绩与模考不同,不与培训班挂钩)
    end
    get :set_real_scores ,on: :member
    get :set_entry_and_target_scores ,on: :member

    get :set_finished_test_papers ,on: :member

    resources :examinations  do #学员包含多个模拟考试
      resources :scores ,only: [:new,:create,:edit,:update]

    end

  end

  resources :examinations  do #培训班包含多个模拟考试
    resources :scores,only: :index  #列出某次特定模考 的所有学员考试成绩

  end

  resources :comments,only:[:destroy]

  resources :training_classes do

    get :add_student ,on: :collection #给培训班添加一个学员,(ajax调用)
    get :remove_student ,on: :collection #给培训班添加一个学员,(ajax调用)
    get :set_students, on: :member #给培训班设置学员 页面
    resources :attendances #考勤

    resources :dictations #听写
    resources :examinations #模拟考
    resources :homeworks #作业

    resources :students do #培训班包含多个学员

      resources :scores ,only: :index #列出某个培训班下 某个学员的 所有模考成绩 (呈现为d3统计报表)

      resources :comments   #讲师/班主任可以给学员创建评语
    end

  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base

  has_many :training_classes,foreign_key: 'master_teacher_id'
  #员工可能登录系统,所以有一个对应的账户
  belongs_to :user


  #定义员工信息时的Form 能够同时定义其登录账户的信息
  accepts_nested_attributes_for :user

  default_scope {where delete_flag: false}

  def name
    self.user.name
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  #员工信息 控制器

  before_action :set_employee, only: [:show, :edit, :update, :destroy,:freezing,:unfreezing,]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    @employee.user =User.new
    @user = @employee.user
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    @employee.user.role_name='员工'
      if @employee.save
         redirect_to employees_path, notice: '员工信息已保存.'

      else
         render :new

      end

  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update

      if @employee.update(employee_params)
        redirect_to employees_path, notice: '员工信息已保存.'

      else
        render :edit

      end

  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.update_attribute(:delete_flag,true)
    redirect_to employees_url, notice: '员工已删除.'
  end
  def freezing
    @employee.update_attribute(:freezing_flag,true)
    redirect_to employees_url, notice: '员工已冻结'
  end

  def unfreezing
    @employee.update_attribute(:freezing_flag,false)
    redirect_to employees_url, notice: '员工已恢复'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
      @user = @employee.user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:admin,user_attributes: [:name,:phone_number,:id,:email, :qq_number,
                                                                :tinypost_number, :photo,
                                                                :identify_card,])
    end


end

app/views/employees/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">

<%= simple_form_for(@employee) do |f| %>
    <%= f.error_notification %>

    <%= f.fields_for(:user) do |user_f| %>


          <div class="field">
            <%= user_f.input :name,label:"名称" %>
          </div>

          <div class="field">
            <%= render 'shared/upload_user_photo', form_builder: user_f%>
          </div>

          <div class="field">
            <%= user_f.input :phone_number,label:"手机号" %>
          </div>
          <div class="field">
            <%= user_f.input :identify_card,label:"身份证号" %>
          </div>

          <div class="field">
            <%= user_f.input :email ,label:"Email"%>
          </div>


          <div class="field">
            <%= user_f.input :tinypost_number ,label:"微信"%>
          </div>

          <div class="field">
            <%= user_f.input :qq_number ,label:"QQ"%>
          </div>


    <% end %>

    <%if current_user.can_manage_basic_data?%>
    <%= f.input :admin ,label:"管理员"%>
    <%end%>
    <div class="form-actions">
      <%= f.button :submit ,'保存',inner_html: {class:"ui blue submit button"} %>

    </div>
<% end %>
    </div>
  </div>
</div>

app/views/employees/edit.html.erb
<div class="page-content page-thin">
<%= render partial: 'shared/page_title_caption', object: "修改员工" %>
<%= render 'form' %>
</div>

app/views/employees/index.html.erb
<div class="page-content page-thin">



<%= render partial: 'shared/page_title_caption', object: "员工列表" %>

<h3>共有员工 <%= @employees.length %> 人</h3>

<table class=" celled table segment">
  <thead>
  <tr>

    <th>姓名</th>
    <th>管理员</th>
    <th>身份证号</th>
    <th>手机号</th>
    <th>QQ</th>
    <th>微信</th>
    <th>电子邮箱</th>

    <%if current_user.can_manage_basic_data?%>
    <th colspan="2"></th>
    <%end%>
  </tr>
  </thead>

  <tbody>
  <% @employees.each do |emp| %>
      <tr>

        <td><%= link_to emp.name, employee_path(emp) %></td>
        <td><%= emp.admin? ? '是':''  %></td>

        <td><%= emp.user.try(:identify_card)  %></td>
        <td><%= emp.user.try(:phone_number)  %></td>
        <td><%= emp.user.try(:qq_number) %></td>
        <td><%= emp.user.try(:tinypost_number)  %></td>
        <td><%= emp.user.try(:email)   %></td>


        <%if current_user.can_manage_basic_data?%>
            <td><%= link_to '修改', edit_employee_path(emp) ,{class:"btn btn-primary"}%></td>
            <td>
            <%if emp.freezing_flag%>
                <%= link_to '解冻', unfreezing_employee_path(emp),{class:"btn btn-primary", method: :patch }%>
            <%else%>
                <%= link_to '冻结', freezing_employee_path(emp),{class:"btn btn-primary", method: :patch }%>
            <%end%>
            <%= link_to '删除', emp, {class:"btn btn-danger",method: :delete, data: { confirm: '确认删除员工?' }} %></td>
        <%end%>

      </tr>
  <% end %>
  </tbody>
</table>

<br>
<%if current_user.can_manage_basic_data?%>
<%= link_to '新建 员工', new_employee_path ,{class:"btn btn-primary"}%>
<%end%>

</div>

app/views/employees/new.html.erb
<div class="page-content page-thin">
  <%= render partial: 'shared/page_title_caption', object: "创建员工" %>

<%= render 'form' %>
</div>

app/views/employees/show.html.erb
<div class="page-content page-thin">
<h1></h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>姓名:</strong>
  <%= @employee.user.name %>
</p>
<p>
  <strong>手机:</strong>
  <%= @employee.user.phone_number %>
</p>

<p>
  <strong>邮箱:</strong>
  <%= @employee.user.email %>
</p>
<p>
  <strong>管理员:</strong>
  <%= @employee.admin ? '是':'否'%>
</p>


<% if current_user.can_set_employee_info?(@employee) %>
    <%= link_to '修改信息', edit_employee_path(@employee), {class: 'ui blue button'}%>
    <%= link_to '设置密码', set_password_user_path(@employee.user), {class: 'ui blue button'}%>
<% end %>

<% if current_user.employee? %>
    <%= link_to '返回到员工列表', employees_path,{class: 'ui blue button'} %>
<% end %>

</div>