config/routes.rb
Rails.application.routes.draw do

  root 'home_page#index'

  namespace :admin do
    get 'home_page/index'
    get 'login'=>'home_page#login' #这个路由页面css效果有问题(原因不知道),目前使用下面的login路由
    get 'home_page/login'
  end

  post 'session/create'
  get 'session/destroy' ,as:'log_out'

  concern :freezingable do  #可继承此概念的路由
    patch :unfreezing, on: :member
    patch :freezing, on: :member
  end

  resources :teachers , concerns: [:freezingable] do
  end

  resources :text_books

  resources :test_papers do    #考试套题包含套题的section
    resources :sections
  end

  resources :subjects

  resources :employees , concerns: [:freezingable]

  resources :users do
    get :set_password , on: :member
  end

  get 'home_page/course_list' =>'home_page#course_list',as:'courseList'
  get 'home_page/lecturer_profile' => 'home_page#lecturer_profile', as:'lecturer_profile'
  get 'home_page/lecturer_list' => 'home_page#lecturer_list', as:'lecturers_intro'

  resources :articles do
    get 'tags/:tag', to: 'articles#index', as: :tag ,on: :collection
  end

  get 'home_page/search'
  get 'home_page/upload'
  get 'home_page/training_class_schedule'
  get 'home_page/delete_schedule'
  post 'home_page/upload'

  get 'home_page/index'
  get 'home_page/reports'
  get 'home_page/big_data_report_scores'
  post 'home_page/big_data_report_scores'

  resources :questions

  resources :students , concerns: [:freezingable] do
    get :search_with_trainingclass,on: :collection # 带培训班id 的学员查询,会从查询结果中过滤掉培训班中已有的学员( 培训班 Set_Students 页面专用)
    get :search , on: :collection

    resources :real_scores do
      get :index_with_all_examinations ,on: :collection #列出某个学员的 所有真实考试成绩 (统计报表)(真实考试成绩与模考不同,不与培训班挂钩)
    end
    get :set_real_scores ,on: :member
    get :set_entry_and_target_scores ,on: :member

    get :set_finished_test_papers ,on: :member

    resources :examinations  do #学员包含多个模拟考试
      resources :scores ,only: [:new,:create,:edit,:update]

    end

  end

  resources :examinations  do #培训班包含多个模拟考试
    resources :scores,only: :index  #列出某次特定模考 的所有学员考试成绩

  end

  resources :comments,only:[:destroy]

  resources :training_classes do

    get :add_student ,on: :collection #给培训班添加一个学员,(ajax调用)
    get :remove_student ,on: :collection #给培训班添加一个学员,(ajax调用)
    get :set_students, on: :member #给培训班设置学员 页面
    resources :attendances #考勤

    resources :dictations #听写
    resources :examinations #模拟考
    resources :homeworks #作业

    resources :students do #培训班包含多个学员

      resources :scores ,only: :index #列出某个培训班下 某个学员的 所有模考成绩 (呈现为d3统计报表)

      resources :comments   #讲师/班主任可以给学员创建评语
    end

  end

end

app/models/dictation.rb
class Dictation < ActiveRecord::Base
  belongs_to :training_class  #属于某个培训班

  has_many :dictation_scores, dependent: :delete_all
  accepts_nested_attributes_for :dictation_scores  ,
                                allow_destroy: true


  default_scope {order('execute_date DESC')}

end

app/controllers/dictations_controller.rb
class DictationsController < ApplicationController
  #听写成绩 控制器
  before_action :set_training_class
  before_action :set_dictation, only: [:show, :edit, :update, :destroy]

  # GET /dictations
  # GET /dictations.json
  def index
    @dictations = @training_class.dictations

    if(params[:student_id])
      @student= Student.find(params[:student_id])
      @stu_diction_scores =@training_class.student_dictions(@student)
      @week_dates = WeekDate.group_days(@stu_diction_scores,@training_class)
      # @student_attendances  =@attendances.student_attendances.where(student_id: @student)

      render "index_for_special_student"
    else
      render "index"
    end
  end

  # GET /dictations/1
  # GET /dictations/1.json
  def show
  end

  # GET /dictations/new
  def new
    @dictation = Dictation.new
    @training_class.students.each do |stu|
        @dictation.dictation_scores.build(student: stu,score:0)
    end
  end

  # GET /dictations/1/edit
  def edit
  end

  # POST /dictations
  # POST /dictations.json
  def create
    @dictation = Dictation.new(dictation_params)
    @dictation.training_class =@training_class

      if @dictation.save
        redirect_to training_class_dictations_path(@training_class) , notice: 'Dictation was successfully created.'
      else
        render :new
      end

  end

  # PATCH/PUT /dictations/1
  # PATCH/PUT /dictations/1.json
  def update

      if @dictation.update(dictation_params)
         redirect_to training_class_dictations_path(@training_class) , notice: 'Dictation was successfully updated.'

      else
        render :edit

      end

  end

  # DELETE /dictations/1
  # DELETE /dictations/1.json
  def destroy
    @dictation.destroy

    redirect_to training_class_dictations_path(@training_class) , notice: 'Dictation was successfully destroyed.'


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dictation
      @dictation = Dictation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dictation_params
      params.require(:dictation).permit(:passing_line, :execute_date,dictation_scores_attributes:[:id,:student_id,:dictation_id,:score])
    end
end

app/helpers/dictation_helper.rb
module DictationHelper
  def helper__summary_dictation_text(dictation)
    #返回所有学员听写情况的简要说明文字
    passline= dictation.passing_line || 0
    pass_count = 0
    not_pass_count = 0
    no_score_count = 0
    dictation.dictation_scores.map{|dict_score|

      __score= dict_score.score || -1
      if __score > passline#听写不合格的学员
        not_pass_count+=1
      elsif __score < 0  #没有听写成绩(未听写)的学员
        no_score_count+=1
      else #听写合格的学员
        pass_count+=1
      end
    }

    #生成描述字符串
    return " 及格#{pass_count}人.不及格#{not_pass_count}人.未听写#{no_score_count}人"
  end


  def helper__css_color_style_dictation_score(dictation_score)
    score = dictation_score.score || -1
    if (score >= dictation_score.dictation.passing_line)
      return 'btn-danger'
    elsif(score>=0)
      return 'btn-success'
    else
      return 'btn-default'
    end
    return ''
  end
end

app/views/dictations/_all_students_dictations_statistics_details.html.erb
<%dictation = all_students_dictations_statistics_details %>
<% passline= dictation.passing_line || 0 %>

<% dictation.dictation_scores.map do |dict_score| %>
<% __score= dict_score.score || -1 %>
<% stu_name_and_dict_score =dict_score.student.name + "(#{__score})" %>
    <div>
    <% if __score > passline #听写不合格的学员%>
        <label class="btn-danger label">
          <%= stu_name_and_dict_score %>
        </label>
    <% elsif __score < 0  #没有听写成绩(未听写)的学员 %>
        <label class="btn-default label">
          <%= dict_score.student.name + "(未听写)" %>
        </label>
    <% else #听写合格的学员 %>
        <label class="btn-success label">
          <%= stu_name_and_dict_score %>
        </label>
    <% end %>
    </div>
<% end %>

app/views/dictations/_form.html.erb
<%= simple_form_for([@training_class,@dictation]) do |f| %>
  <%= f.error_notification %>

<div class="ui five fields">

        <div class="field">
    <%= f.input :passing_line ,label:'听写合格线'%>
        </div>
        <div class="field">
    <%= f.input :execute_date,label:'听写日期' %>
        </div>


</div>
    <div class="ui ribbon green label">
      <label>如果学员未听写,输入 -1 </label>
    </div>
    <%= f.fields_for(:dictation_scores) do |dict_scores_form|%>
        <%student =dict_scores_form.object.student%>
        <div class="ui inline fields">

          <div class="field ">
            <%= dict_scores_form.input_field :student_id, type:'hidden' %>
          </div>

          <div class="field ">
            <%= dict_scores_form.input :score,{label: "#{student.name } 听写错误数:",inner_html:{class:"ui red label"}}          %>
          </div>
        </div>
    <% end %>

  <div class="form-actions">
    <%= f.button :submit ,'保存听写成绩'%>
  </div>
<% end %>

app/views/dictations/edit.html.erb
<div class="page-content page-thin">
  <%= render partial: 'shared/page_title_caption', object: "修改听写成绩" %>

<%= render 'form' %>

<%= link_to '返回到听写列表', training_class_dictations_path(@training_class) ,{class:'ui blue button'}%>
</div>

app/views/dictations/index.html.erb
<div class="page-content page-thin">
  <%= render partial: 'shared/page_title_caption', object: "培训班#{@training_class.name} 的听写成绩" %>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <% index_counter =0 %>
        <% @dictations.each do |dictation| %>
            <% index_counter = index_counter+1 %>
            <div class="row">
              <div class="col-md-12">
                <div>
                  <span>
                    <%= dictation.execute_date %> &nbsp;合格线:<%= dictation.passing_line %>
                  </span>
                </div>

                <% if current_user.is_training_class_master?(@training_class) %>
                    <%= link_to "修改", edit_training_class_dictation_path(@training_class, dictation), {class: 'btn btn-success'} %></td>
                    <%= link_to '删除听写信息', training_class_dictation_path(@training_class, dictation), {class: 'btn btn-danger', method: :delete, data: {confirm: '确定删除听写记录?'}} %>
                <% end %>
                <% summary_info =helper__summary_dictation_text(dictation) %>

                <div data-remark="输出折叠项">
                  <% accordion_id ="accordion_#{index_counter}" %>
                  <!--某天的所有学员听写情况统计-->
                  <% content_for "#{accordion_id}_item_1".to_sym do %>
                      <%= render partial: 'all_students_dictations_statistics_details', object: dictation %>
                  <% end %>
                  <%= render 'shared/compoment_template_accordion', object: {accordion_id: accordion_id, item_titles: ["#{summary_info}"]} %>
                </div>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>


  <br>
  <% if current_user.is_training_class_master?(@training_class) %>
      <%= link_to '创建听写成绩', new_training_class_dictation_path(@training_class), {class: 'btn btn-primary'} %>
      <br>
  <% end %>
</div>

app/views/dictations/index_for_special_student.html.erb
<div class="page-content page-thin">

  <%= render partial: 'shared/page_title_caption', object: "学员#{@student.name}在培训班 #{@training_class.name } 的听写成绩" %>





  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-6">
            <div>
              <label class="theme-color-label"> 班级开课时间:<%= @training_class.start_date %>
                至 <%= @training_class.end_date %></label>
            </div>
            <div>
              <label class="btn-success">
                合格
              </label>
              <label class="btn-danger">
                不合格
              </label>
              <label class="btn-default">
                未听写
              </label>
            </div>

          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <table class="table table-bordered">
              <thead>
              <tr>
                <th>周日</th>
                <th>周一</th>
                <th>周二</th>
                <th>周三</th>
                <th>周四</th>
                <th>周五</th>
                <th>周六</th>


              </tr>
              </thead>

              <tbody>

              <% @week_dates.each do |week| %>
                  <tr>
                    <% 7.times do |i| %>
                        <% str_css, str_description ='', '' %>
                        <% if week.has_day_dictation_score?(i) %>
                            <% dictation_score = week.get_student_dictation_score_with_day(i) %>
                            <% str_css = helper__css_color_style_dictation_score(dictation_score) %>
                            <% str_description = dictation_score.description %>
                        <% end %>


                        <td class="<%= str_css %>">
                          <%= week.get_day(i).strftime("%m-%d") if week.get_day(i) >= @training_class.start_date && week.get_day(i)<= @training_class.end_date %>
                          <br><%= str_description %>
                        </td>
                    <% end %>
                    <tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  </div>




  <%= link_to '返回到我的培训班列表', training_classes_path, {class: 'ui blue button'} %>
</div>

app/views/dictations/new.html.erb
<div class="page-content page-thin">
  <%= render partial: 'shared/page_title_caption', object: "创建听写成绩" %>

<%= render 'form' %>

<%= link_to '返回到听写列表', training_class_dictations_path(@training_class),{class:'ui blue button'} %>
</div>

app/views/dictations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Passing line:</strong>
  <%= @dictation.passing_line %>
</p>

<p>
  <strong>Execute date:</strong>
  <%= @dictation.execute_date %>
</p>

<%= link_to 'Edit', edit_dictation_path(@dictation) %> |
<%= link_to 'Back', dictations_path %>