config/routes.rb
Rails.application.routes.draw do

  root 'home_page#index'

  namespace :admin do
    get 'home_page/index'
    get 'login'=>'home_page#login' #这个路由页面css效果有问题(原因不知道),目前使用下面的login路由
    get 'home_page/login'
  end

  post 'session/create'
  get 'session/destroy' ,as:'log_out'

  concern :freezingable do  #可继承此概念的路由
    patch :unfreezing, on: :member
    patch :freezing, on: :member
  end

  resources :teachers , concerns: [:freezingable] do
  end

  resources :text_books

  resources :test_papers do    #考试套题包含套题的section
    resources :sections
  end

  resources :subjects

  resources :employees , concerns: [:freezingable]

  resources :users do
    get :set_password , on: :member
  end

  get 'home_page/course_list' =>'home_page#course_list',as:'courseList'
  get 'home_page/lecturer_profile' => 'home_page#lecturer_profile', as:'lecturer_profile'
  get 'home_page/lecturer_list' => 'home_page#lecturer_list', as:'lecturers_intro'

  resources :articles do
    get 'tags/:tag', to: 'articles#index', as: :tag ,on: :collection
  end

  get 'home_page/search'
  get 'home_page/upload'
  get 'home_page/training_class_schedule'
  get 'home_page/delete_schedule'
  post 'home_page/upload'

  get 'home_page/index'
  get 'home_page/reports'
  get 'home_page/big_data_report_scores'
  post 'home_page/big_data_report_scores'

  resources :questions

  resources :students , concerns: [:freezingable] do
    get :search_with_trainingclass,on: :collection # 带培训班id 的学员查询,会从查询结果中过滤掉培训班中已有的学员( 培训班 Set_Students 页面专用)
    get :search , on: :collection

    resources :real_scores do
      get :index_with_all_examinations ,on: :collection #列出某个学员的 所有真实考试成绩 (统计报表)(真实考试成绩与模考不同,不与培训班挂钩)
    end
    get :set_real_scores ,on: :member
    get :set_entry_and_target_scores ,on: :member

    get :set_finished_test_papers ,on: :member

    resources :examinations  do #学员包含多个模拟考试
      resources :scores ,only: [:new,:create,:edit,:update]

    end

  end

  resources :examinations  do #培训班包含多个模拟考试
    resources :scores,only: :index  #列出某次特定模考 的所有学员考试成绩

  end

  resources :comments,only:[:destroy]

  resources :training_classes do

    get :add_student ,on: :collection #给培训班添加一个学员,(ajax调用)
    get :remove_student ,on: :collection #给培训班添加一个学员,(ajax调用)
    get :set_students, on: :member #给培训班设置学员 页面
    resources :attendances #考勤

    resources :dictations #听写
    resources :examinations #模拟考
    resources :homeworks #作业

    resources :students do #培训班包含多个学员

      resources :scores ,only: :index #列出某个培训班下 某个学员的 所有模考成绩 (呈现为d3统计报表)

      resources :comments   #讲师/班主任可以给学员创建评语
    end

  end

end

app/models/score.rb
class Score < ActiveRecord::Base

  include BaseScore  #添加了 totalscore,sat_cr_score,toefl_listening_score等关于分数数值的属性

#模拟考试得分
  belongs_to :examination  #属于某次模拟考试
  belongs_to :student    #属于某个学员类型的user
  has_many :score_details  #明细记录了每道题的对错情况

  accepts_nested_attributes_for :score_details  ,
                                allow_destroy: true


  @questions_group_by_section= Hash.new {|hash, key| hash[key] = []}

  def questions_GroupBySection #此方法暂时未用
    @questions_group_by_section
  end


end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  #模考分数 控制器
  before_action :set_simulate_test_score, only: [:show, :edit, :update, :destroy]
  before_action :find_student,except: [:index]
  before_action :find_simulate_test, except:[:index,:index_with_all_examinations]


  # GET /scores
  # GET /scores.json
  def index
    #提供了培训班id,学员id,则 index 呈现 指定培训班下的/指定学员的/所有模考成绩
    if (params[:student_id] && params[:training_class_id])
      @student =Student.find(params[:student_id])
      @training_class =TrainingClass.find(params[:training_class_id])
      @examinations =@training_class.examinations
      @scores=@student.scores

      # render layout:'application2', template: 'scores/index_with_all_examinations'
      render 'index_with_all_examinations'

    elsif (params[:examination_id]) #指定了某次模考,则index 呈现关于此次模考所有有此模考成绩(所有学员的)
      @examination =Examination.find(params[:examination_id])
      @training_class =@examination.training_class
      @training_class_students =@training_class.students
      @scores=@examination.scores
      # render layout:'application2', template:  'scores/index_for_all_students'
      render 'index_for_all_students'
    else #默认情况下,则呈现数据库的所有 score 记录


    end
  end


  #GET  /training_classes/:training_class_id/examinations/:examination_id/scores/index_for_all_students(.:format)
  # def index_for_all_students
  #
  #   #模考特定,列出本次模考的所有学员的成绩
  #
  #
  #   @examination =Examination.find(params[:examination_id])
  #
  #   @training_class =@examination.training_class
  #
  #   @training_class_students =@training_class.students
  #
  #   @scores=@examination.scores
  #
  #
  # end

  # def index_with_all_examinations
  #
  #   #学员特定,列出学员的所有模考成绩
  #   @student =Student.find(params[:student_id])
  #
  #   @training_class =TrainingClass.find(params[:training_class_id])
  #   @examinations =@training_class.examinations
  #   @scores=@student.scores
  #
  #
  # end


  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
    if @training_class.exam_type=='SAT'
      @score.course_a_score=0 #CR总分
      @score.stat_01 =19 # CR 词汇 : 正确数量
      @score.stat_02 =0 # CR 词汇 : 错误数量
      @score.stat_03 =0 # CR 词汇 : 空题数量
      @score.stat_04 =48 # CR 阅读 : 正确数量
      @score.stat_05 =0 # CR 阅读 : 错误数量
      @score.stat_06 =0 # CR 阅读 : 空题数量
      @score.stat_07 =67 # CR raw score

      @score.course_b_score=0 #数学得分
      @score.stat_08 =54 # 数学: 正确数量
      @score.stat_09 =0 # 数学 : 错误数量
      @score.stat_10 =0 # 数学 : 空题数量
      @score.stat_11 =54 # 数学 raw score

      @score.course_c_score=0 #写作得分
      @score.stat_12 =49 # 写作 : 正确数量
      @score.stat_13 =0 # 写作 : 错误数量
      @score.stat_14 =0 # 写作 : 空题数量
      @score.stat_15 =49 # 写作 raw score
      @score.stat_16 =0 # 写作 作文得分

      @score.final_score =0
    elsif @training_class.exam_type=='TOEFL'
      @score.course_a_score=0 #听总分
      @score.course_b_score=0 #说总分
      @score.course_c_score=0 #读总分
      @score.course_d_score=0 #写总分
    end
    @score.examination =@examination
    @score.student =@student
    @test_paper.sections.each do |section|
       section.questions.each do |question|
         @score.score_details.build({question: question})
       end
    end

  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create


    @score = Score.new(simulate_test_score_params)

    if @score.save

      redirect_to examination_scores_path(@examination),
                notice: '模考成绩已保存'

    end

  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(simulate_test_score_params)


        format.html { redirect_to examination_scores_path(@examination),notice: '学员成绩己记录.'  }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to examination_scores_url, notice: 'Simulate test score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private


    def find_simulate_test
      @examination= Examination.find(params[:examination_id])
      @training_class =@examination.training_class
      @test_paper =@examination.test_paper

    end
    def find_student
      @student =Student.find(params[:student_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_simulate_test_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def simulate_test_score_params
      params.require(:score).permit(:examination_id, :student_id,:final_score,

                                    :cr_score,:math_score, :writing_score, :essay_writing_score,

                                    :course_a_score,:course_b_score,:course_c_score,:course_d_score,

                                    :stat_01,:stat_02,:stat_03,:stat_04,:stat_05,:stat_06,:stat_07,:stat_08,:stat_09,
                                    :stat_10,:stat_11,:stat_12,:stat_13,:stat_14,:stat_15,:stat_16,
                                    :hard_level1,:hard_level2,:hard_level3,:hard_level4,:hard_level5,

                                    score_details_attributes: [:id,:answer_result,:score_number,:section_question_id])
    end
end

app/helpers/scores_helper.rb
module ScoresHelper



  def can_view_subject(subject_name,training_class,user)
    #判断某个用户是否有权限看到某科目的(成绩,作业等)信息
    return true unless user.teacher?

    return user.teacher.subjects.where(training_class_id: training_class.id).any? do |subject|
       subject.name ==subject_name
    end
  end

  def wrap_scores_for_nvd3_chart(scores_2d_arr,training_class,current_user)
    return_arr=[]
    cr_scores = []
    math_scores = []
    writing_scores=[]
    listen_scores = []
    talk_scores = []
    read_scores = []

    exam_type =training_class.exam_type

    scores_2d_arr.each do |arr_element|
        key_str=arr_element[0]
        value_score= arr_element[1]
        if exam_type =='SAT'
            cr_scores      << {x:key_str,y:value_score.course_a_score}
            math_scores    << {x:key_str,y:value_score.course_b_score}
            writing_scores << {x:key_str,y:value_score.course_c_score}
        elsif exam_type == 'TOEFL'
           listen_scores   << {x:key_str,y:value_score.course_a_score}
           talk_scores     << {x:key_str,y:value_score.course_b_score}
           read_scores     << {x:key_str,y:value_score.course_c_score}
           writing_scores  << {x:key_str,y:value_score.course_d_score}
        end
      end

    if exam_type =='SAT'
      return_arr << {key:'CR',values:cr_scores}  if can_view_subject('CR',training_class,current_user)
      return_arr << {key:'Math',values:math_scores}  if can_view_subject('Marh',training_class,current_user)
      return_arr << {key:'Writing',values:writing_scores}  if can_view_subject('Grammar',training_class,current_user)


    elsif exam_type == 'TOEFL'
      return_arr << {key:'Listening',values:listen_scores}  if can_view_subject('Listening',training_class,current_user)

      return_arr << {key:'Speaking',values:talk_scores}  if can_view_subject('Speaking',training_class,current_user)

      return_arr << {key:'Reading',values:read_scores}  if can_view_subject('Reading',training_class,current_user)

      return_arr << {key:'Writing',values:writing_scores}  if can_view_subject('Writing',training_class,current_user)

    end

    return return_arr

  end

  def all_student_simulate_scores_in_one_examation(exam_type,scores)
    return_2D_arr =[]
    #插入模考成绩
    scores.each do |score|
      total_score = score.total_score(exam_type)
      return_2D_arr<<  ["#{score.student.name}(#{total_score})",score]
    end

    return return_2D_arr

  end
  def student_simulate_scores_in_a_training_class(student,training_class,exam_type)
    return_2D_arr =[]
    #学员所属培训班的模考成绩
    scores= student.scores.joins(:examination).where(examinations:{training_class_id:training_class})

    if exam_type =='SAT'
      real_score_entry = student.real_scores.sat.entry.first
      real_score_target = student.real_scores.sat.target.first
    elsif exam_type=='TOEFL'
      real_score_entry = student.real_scores.toefl.entry.first
      real_score_target = student.real_scores.toefl.target.first
    end

    #插入入口成绩
    unless real_score_entry.nil?
      total_score =real_score_entry.total_score(exam_type)
      return_2D_arr << ["入口成绩(#{total_score})",real_score_entry]
    end

    #插入期望成绩
    unless real_score_target.nil?
      total_score =real_score_target.total_score(exam_type)
      return_2D_arr << ["最终期望成绩(#{total_score})",real_score_target]
    end


    #插入模考成绩

    scores.each_with_index do |score,i |


      total_score = score.total_score(exam_type)
      return_2D_arr<<  ["模考#{i + 1 }(#{total_score})",score]
    end



    #数量不够,补足一些空数据(为了报表的好看性)
    num = 15-(return_2D_arr.count)
    simulate_scores_count= scores.count

    if num>0
      num.times{|i|
        temp_score=Score.new({course_a_score:0,course_b_score:0,course_c_score:0,course_d_score:0})
        return_2D_arr<<  ["模考#{simulate_scores_count + 1 + i }",temp_score]
      }
    end
    return return_2D_arr

  end




  def scores_objects_for_nvd3_chart(student,z_training_class)
    objs =[]

    scores= student.scores.joins(:examination).where(examinations:{training_class_id:z_training_class})
    scores_count =scores.count

    if z_training_class.exam_type =='SAT'
      cr_scores = []
      math_scores = []
      grammar_scores = []
      #插入入口成绩
      real_score = student.real_scores.sat.entry.first
      unless real_score.nil?
        total_score = real_score.course_a_score + real_score.course_b_score+ real_score.course_c_score
        cr_scores<<{x:"入口成绩(#{total_score})",y:real_score.course_a_score}
        math_scores<<{x:"入口成绩(#{total_score})",y:real_score.course_b_score}
        grammar_scores<<{x:"入口成绩(#{total_score})",y:real_score.course_c_score}

      end

      real_score = student.real_scores.sat.target.first
      unless real_score.nil?

        total_score = real_score.course_a_score + real_score.course_b_score+ real_score.course_c_score


        cr_scores<<{x:"最终期望成绩(#{total_score})",y:real_score.course_a_score}
        math_scores<<{x:"最终期望成绩(#{total_score})",y:real_score.course_b_score}
        grammar_scores<<{x:"最终期望成绩(#{total_score})",y:real_score.course_c_score}

      end


      fix_num = cr_scores.count #fix_num值为入口成绩和目标成绩的数量

      #插入模考成绩
      scores.each_with_index do |score,i |
        total_score = score.course_a_score + score.course_b_score+ score.course_c_score


        cr_scores<<  {x:"模考#{i + 1 }(#{total_score})",y: score.course_a_score}
        math_scores<<  {x:"模考#{i + 1}(#{total_score})",y: score.course_b_score}
        grammar_scores<<  {x:"模考#{i + 1}(#{total_score})",y: score.course_c_score}
      end



      #插入更多未考的模考成绩
      num = 15-(scores_count+fix_num)
      if num>0
        num.times{|i|
        cr_scores<<{x:"模考#{scores_count + 1 + i }",y:0}
        math_scores<<{x:"模考#{scores_count + 1 + i }",y:0}
        grammar_scores<<{x:"模考#{scores_count + 1 + i }",y:0}
        }
      end

      objs=[{key:'阅读',values:cr_scores},{key:'数学',values:math_scores},{key:'语法',values:grammar_scores}]



    elsif z_training_class.exam_type =='TOEFL'

      listen_scores = []
      talk_scores = []
      read_scores = []
      writing_scores=[]

      real_score = student.real_scores.toefl.entry.first
      unless real_score.nil?
        listen_scores<<{x:'入口成绩',y:real_score.course_a_score}
        talk_scores<<{x:'入口成绩',y:real_score.course_b_score}
        read_scores<<{x:'入口成绩',y:real_score.course_c_score}
        writing_scores<<{x:'入口成绩',y:real_score.course_d_score}
      end
      #插入入口成绩
      real_score = student.real_scores.toefl.target.first
      unless real_score.nil?
        listen_scores<<{x:'最终期望成绩',y:real_score.course_a_score}
        talk_scores<<{x:'最终期望成绩',y:real_score.course_b_score}
        read_scores<<{x:'最终期望成绩',y:real_score.course_c_score}
        writing_scores<<{x:'最终期望成绩',y:real_score.course_d_score}

      end

      #插入目标成绩 理想目标和某月目标的值
      #...
      #...

      fix_num = listen_scores.count #fix_num值为入口成绩和目标成绩的数量

      #插入模考成绩
      scores.each_with_index do |score,i |
        listen_scores<<  {x:"模考#{i + 1 }",y: score.course_a_score}
        talk_scores<<  {x:"模考#{i + 1}",y: score.course_b_score}

        read_scores<<  {x:"模考#{i + 1}",y: score.course_c_score}
        writing_scores<<  {x:"模考#{i + 1}",y: score.course_d_score}
      end


      num = 15-(scores_count+fix_num)
      if num>0
        num.times{|i|
          listen_scores<<{x:"模考#{scores_count + 1 + i }",y:0}
          talk_scores<<{x:"模考#{scores_count + 1 + i }",y:0}
          read_scores<<{x:"模考#{scores_count + 1 + i }",y:0}
          writing_scores<<{x:"模考#{scores_count + 1 + i }",y:0}
        }
      end

      objs=[{key:'听力',values:listen_scores},{key:'口语',values:talk_scores},{key:'阅读',values:read_scores},{key:'写作',values:writing_scores}]
    end
    return objs
  end

end

app/views/scores/_index_for_all_students_sat.html.erb
<!--本局部视图属于 index_for_all_students.html.erb ,用于显示所有学员的某次特定模拟考试的(SAT)成绩列表-->

<table class ="ui celled table segment">
  <thead>
  <tr>

    <th></th>
    <th>总分</th>

    <%if can_view_subject('CR' , @training_class,current_user) %>
        <th  colspan="8">Critical Reading</th>
    <%end%>

    <%if can_view_subject('Math' , @training_class,current_user) %>
        <th  colspan="5">Mathematics</th>
    <%end%>

    <%if can_view_subject('Grammar' , @training_class,current_user) %>
        <th colspan="6">Writing </th>
    <%end%>

    <th></th>
  </tr>
  </thead>
  <tr>

    <th>学员</th>
    <th></th>

    <%if can_view_subject('CR' , @training_class,current_user) %>
    <th>CR总分 </th> <th>raw score </th>
    <th>词汇<i class="green checkmark icon"></i> </th> <th>词汇<i class="red close icon"></i> </th><th>词汇<i class="teal minus icon"></i> </th>
    <th>阅读<i class="green checkmark icon"></i> </th> <th>阅读<i class="red close icon"></i> </th><th>阅读<i class="teal minus icon"></i> </th>
    <%end%>

    <%if can_view_subject('Math' , @training_class,current_user) %>
    <th>Math总分 </th> <th>raw score </th>
    <th> <i class="green checkmark icon"></i> </th> <th><i class="red close icon"></i> </th><th><i class="teal minus icon"></i> </th>
    <%end%>

    <%if can_view_subject('Grammar' , @training_class,current_user) %>
    <th>Writing 得分</th><th>raw score </th>
    <th> <i class="green checkmark icon"></i> </th> <th><i class="red close icon"></i> </th><th><i class="teal minus icon"></i> </th>
    <th>作文</th>
    <%end%>
    <th></th>
  </tr>
  <tbody>

  <% @training_class_students.each do |student| %>

      <% score = @scores.where(student_id: student).first %>


      <tr>
        <td><%= student.name %></td>

        <td class="lightgreen"><%= score.try(:final_score) %> </td>
        <%if can_view_subject('CR' , @training_class,current_user) %>
            <td class="normal_blue"><%= score.try(:course_a_score) %></td>
            <td><%= score.try(:stat_07) %></td>
            <td><%= score.try(:stat_01) %></td>
            <td><%= score.try(:stat_02) %></td>
            <td><%= score.try(:stat_03) %></td>
            <td><%= score.try(:stat_04) %></td>
            <td><%= score.try(:stat_05) %></td>
            <td><%= score.try(:stat_06) %></td>
        <%end%>

        <%if can_view_subject('Math' , @training_class,current_user) %>
            <td class="orange"><%= score.try(:course_b_score) %></td>
            <td><%= score.try(:stat_11) %></td>
            <td><%= score.try(:stat_08) %></td>
            <td><%= score.try(:stat_09) %></td>
            <td><%= score.try(:stat_10) %></td>
        <%end%>

        <%if can_view_subject('Grammar' , @training_class,current_user) %>
            <td class="green"><%= score.try(:course_c_score) %></td>
            <td><%= score.try(:stat_15) %></td>
            <td><%= score.try(:stat_12) %></td>
            <td><%= score.try(:stat_13) %></td>
            <td><%= score.try(:stat_14) %></td>
            <td><%= score.try(:stat_16) %></td>
        <%end%>


        <% if current_user.teacher? %>
             <td></td>
        <% else %>
            <td>
            <%=
               if score.nil?
                 link_to(new_student_examination_score_path(student,@examination),{class:'ui green icon button popup_tip_button',"data-content"=>"录入#{student.name}的模拟考试成绩"})do
                   raw( '<i class="edit icon"> </i>')
                 end
               else
                 link_to(edit_student_examination_score_path(student,@examination,score) ,{class:'ui green icon button popup_tip_button',"data-content"=>"修改#{student.name}的模拟考试成绩"}) do
                   raw( '<i class="edit icon"> </i>')
                 end
               end
            %>
            </td>
        <% end %>


      </tr>
  <% end %>
  </tbody>
</table>

app/views/scores/_index_for_all_students_toefl.html.erb
<!--本局部试图属于 index_for_all_students.html.erb ,用于显示所有学员的某次特定模拟考试的(TOEFL)成绩列表-->
<table class ="ui celled table segment">
  <thead>
  <tr>

    <th></th>
    <th >总分</th>


    <% if can_view_subject('Listening' , @training_class,current_user) %>
    <th colspan="3" >听力 </th>
    <% end %>

    <%if can_view_subject('Speaking' , @training_class,current_user) %>
    <th colspan="4" >口语 </th>
    <% end %>
    <%if can_view_subject('Reading' , @training_class,current_user) %>
        <th colspan="3" >阅读</th>
    <%end %>

    <%if can_view_subject('Writing' , @training_class,current_user) %>
    <th colspan="3" >写作 </th>
    <% end %>

    <th></th>
  </tr>
  </thead>
  <tr>

    <th>学员</th>
    <th ></th>

    <% if can_view_subject('Listening' , @training_class,current_user) %>
    <th>听力总分 </th><th> <i class="green checkmark icon"></i> </th><th> <i class="red close icon"></i> </th>
        <%end%>

    <% if can_view_subject('Speaking' , @training_class,current_user) %>
    <th>口语总分 </th><th>1,2题 </th><th>3,4题 </th><th>5,6题 </th>
        <%end%>

    <% if can_view_subject('Reading' , @training_class,current_user) %>
        <th>阅读总分 </th><th> <i class="green checkmark icon"></i> </th> <th> <i class="red close icon"></i> </th>
    <% end %>

    <% if can_view_subject('Writing' , @training_class,current_user) %>
    <th>作文总分 </th><th>综合写作 </th><th>独立写作 </th>

    <%end%>
    <th></th>
  </tr>
  <tbody>
  <% @training_class_students.each do |student| %>

      <% score = @scores.where(student_id: student).first %>

      <tr>
        <td><%= student.name %> </td>


        <td class="lightgreen"><%= score.try(:final_score) %> </td>

        <!--听力-->
        <% if can_view_subject('Listening' , @training_class,current_user) %>
        <td class="normal_blue"><%= score.try(:course_a_score) %></td>
        <td><%= score.try(:stat_01) %></td>
        <td><%= score.try(:stat_02) %></td>
            <%end%>
        <!--口语-->
        <% if can_view_subject('Speaking' , @training_class,current_user) %>
        <td class="orange"><%= score.try(:course_b_score) %></td>
        <td><%= score.try(:stat_03) %></td>
        <td><%= score.try(:stat_04) %></td>
        <td><%= score.try(:stat_05) %></td>

            <%end%>

        <!--阅读-->
        <% if can_view_subject('Reading' , @training_class,current_user) %>
            <td class="green"><%= score.try(:course_c_score) %></td>
            <td><%= score.try(:stat_06) %></td>
            <td><%= score.try(:stat_07) %></td>
        <%end%>

        <% if can_view_subject('Writing' , @training_class,current_user) %>
        <!--写作-->
        <td class="purple_gray"><%= score.try(:course_d_score) %></td>
        <td><%= score.try(:stat_08) %></td>
        <td><%= score.try(:stat_09) %></td>

        <%end%>
        <% if current_user.teacher? %>
            <td></td>

        <% else %>
            <td>
              <%=
                 if score.nil?
                   link_to(new_student_examination_score_path(student,@examination),{class:'ui green icon button popup_tip_button',"data-content"=>"录入#{student.name}的模拟考试成绩"})do
                     raw( '<i class="edit icon"> </i>')
                   end
                 else
                   link_to(edit_student_examination_score_path(student,@examination,score) ,{class:'ui green icon button popup_tip_button',"data-content"=>"修改#{student.name}的模拟考试成绩"}) do
                     raw( '<i class="edit icon"> </i>')
                   end

                 end
              %>
            </td>
        <% end %>


      </tr>
  <% end %>
  </tbody>
</table>

app/views/scores/edit.html.erb
<h1></h1>
<div class="ui horizontal label"><h2> 修改学员 <%=@student.name %> 的模考成绩</h2></div>
<%= render 'form' %>


<%= link_to '返回到班级模考成绩列表',
            examination_scores_path(@examination),
         {class:"ui blue  button"}
%>

app/views/scores/index.html.erb
本页面展示所有模考成绩(所有学员,所有班级,所有模考)

app/views/scores/index_for_all_students.html.erb
<!--#此页面展示 指定培训班的 某次模考的 所有学员的 模考成绩 列表-->
<!--如果是校长,员工查看本页面,则可以看到所有科目成绩,以及进行所有操作-->
<!--如果是讲师,则讲师只能看到自己负责科目的学员模考成绩-->

<div class="page-content page-thin">

<h2>
  <span class="label theme-color-label">[<%=@training_class.exam_type %>培训班]<%=@training_class.name %> 模考成绩列表</span></h2>


  <p>

  <span class="label theme-color-label">[模拟考]<%=@examination.name %> <%=@examination.id %></span>
  </p>
<p>
<span class="label theme-color-label">[试卷]<%= @examination.test_paper.name %></span>
</p>
  <p>
 <span class="label theme-color-label">[考试时间]<%= @examination.test_date %></span>
  </p>
  <p>
 <span class="label theme-color-label">[学员数量]<%= @training_class.students.count %>人</span>
  </p>

<h3>成绩列表:</h3>

<script>
    <%scores = all_student_simulate_scores_in_one_examation(@training_class.exam_type,@scores)%>

    data_example =<%= raw wrap_scores_for_nvd3_chart(scores,@training_class,current_user).to_json%>

</script>

<div id='chart1'>
  <svg style='height:500px'> </svg>
  <!--生成统计报表-->
</div>
<br>
<br>


<%if  @training_class.exam_type == 'SAT' %>

    <%= render 'index_for_all_students_sat'%>


   <% elsif @training_class.exam_type == 'TOEFL' %>

    <%= render 'index_for_all_students_toefl'%>

<%end%>

<%= link_to '返回到班级模考 列表', training_class_examinations_path(@training_class) , {class:"btn btn-primary"}%>
<%= link_to '返回到班级列表', training_classes_path , {class:"btn btn-primary"}%>

<script src="/assets/multiBar.js"></script>


</div>

app/views/scores/new.html.erb
<h1></h1>
<div class="ui horizontal label"><h2> 录入学员 <%=@student.name %>  的模考成绩</h2></div>
<%= render 'form' %>


<%= link_to '返回到班级模考成绩列表',
            examination_scores_path(@examination),
            {class:"ui blue  button"}
%>