config/routes.rb
Rails.application.routes.draw do

  root 'home_page#index'

  namespace :admin do
    get 'home_page/index'
    get 'login'=>'home_page#login' #这个路由页面css效果有问题(原因不知道),目前使用下面的login路由
    get 'home_page/login'
  end

  post 'session/create'
  get 'session/destroy' ,as:'log_out'

  concern :freezingable do  #可继承此概念的路由
    patch :unfreezing, on: :member
    patch :freezing, on: :member
  end

  resources :teachers , concerns: [:freezingable] do
  end

  resources :text_books

  resources :test_papers do    #考试套题包含套题的section
    resources :sections
  end

  resources :subjects

  resources :employees , concerns: [:freezingable]

  resources :users do
    get :set_password , on: :member
  end

  get 'home_page/course_list' =>'home_page#course_list',as:'courseList'
  get 'home_page/lecturer_profile' => 'home_page#lecturer_profile', as:'lecturer_profile'
  get 'home_page/lecturer_list' => 'home_page#lecturer_list', as:'lecturers_intro'

  resources :articles do
    get 'tags/:tag', to: 'articles#index', as: :tag ,on: :collection
  end

  get 'home_page/search'
  get 'home_page/upload'
  get 'home_page/training_class_schedule'
  get 'home_page/delete_schedule'
  post 'home_page/upload'

  get 'home_page/index'
  get 'home_page/reports'
  get 'home_page/big_data_report_scores'
  post 'home_page/big_data_report_scores'

  resources :questions

  resources :students , concerns: [:freezingable] do
    get :search_with_trainingclass,on: :collection # 带培训班id 的学员查询,会从查询结果中过滤掉培训班中已有的学员( 培训班 Set_Students 页面专用)
    get :search , on: :collection

    resources :real_scores do
      get :index_with_all_examinations ,on: :collection #列出某个学员的 所有真实考试成绩 (统计报表)(真实考试成绩与模考不同,不与培训班挂钩)
    end
    get :set_real_scores ,on: :member
    get :set_entry_and_target_scores ,on: :member

    get :set_finished_test_papers ,on: :member

    resources :examinations  do #学员包含多个模拟考试
      resources :scores ,only: [:new,:create,:edit,:update]

    end

  end

  resources :examinations  do #培训班包含多个模拟考试
    resources :scores,only: :index  #列出某次特定模考 的所有学员考试成绩

  end

  resources :comments,only:[:destroy]

  resources :training_classes do

    get :add_student ,on: :collection #给培训班添加一个学员,(ajax调用)
    get :remove_student ,on: :collection #给培训班添加一个学员,(ajax调用)
    get :set_students, on: :member #给培训班设置学员 页面
    resources :attendances #考勤

    resources :dictations #听写
    resources :examinations #模拟考
    resources :homeworks #作业

    resources :students do #培训班包含多个学员

      resources :scores ,only: :index #列出某个培训班下 某个学员的 所有模考成绩 (呈现为d3统计报表)

      resources :comments   #讲师/班主任可以给学员创建评语
    end

  end

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  #讲师可以教多门科目课程从而属于多个培训班(同时培训班包含多个讲师)
  has_many :subjects
  has_many :training_classes ,through: :subjects


  has_many :homeworks  #讲师会布置多套作业，学员会完成多套作业


  #讲师可能登录系统,所以有一个对应的账户
  belongs_to :user

  #定义讲师信息时的Form 能够同时定义其登录账户的信息
  accepts_nested_attributes_for :user
  default_scope {where delete_flag: false}


  def name
    self.user.name
  end

  def is_teach_subject?(training_class,subject_name)
    #判断讲师是否讲授指定培训班的某个科目,参数 training_class 培训班对象, subject_name 符号对象 :sat_cr / :sat_math / :toefl_listen
    return training_class.subject_teachers(subject_name).any?{|teacher| teacher.id == self.id}
  end


end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  #讲师控制器
  before_action :set_teacher, only: [:show, :edit, :update, :destroy,:freezing,:unfreezing,]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
    @teacher.user =User.new
    @user = @teacher.user
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)
      if @teacher.save
        redirect_to teachers_url, notice: '讲师已创建.'
      else
        render :new
      end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update

      if @teacher.update(teacher_params)
         redirect_to teachers_url, notice: '讲师信息已保存.'

      else
         render :edit

      end

  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy

    @teacher.update_attribute(:delete_flag,true)
    redirect_to teachers_url, notice: '讲师已删除.'


  end
  def freezing
    @teacher.update_attribute(:freezing_flag,true)
    redirect_to teachers_url, notice: '讲师已冻结'
  end

  def unfreezing
    @teacher.update_attribute(:freezing_flag,false)
    redirect_to teachers_url, notice: '讲师已恢复'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
      @user = @teacher.user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(  user_attributes: [:name,:email,:phone_number,:id, :qq_number,
                                                          :tinypost_number, :photo,
                                                          :identify_card])
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
<%= simple_form_for(@teacher) do |f| %>
    <%= f.error_notification %>

    <%= f.fields_for(:user) do |user_f| %>


          <div class="field">
            <%= user_f.input :name,label:"名称" %>
          </div>

          <div class="field">
            <%= render 'shared/upload_user_photo', form_builder: user_f%>
          </div>



          <div class="field">
            <%= user_f.input :phone_number,label:"手机号" %>
          </div>

          <div class="field">
            <%= user_f.input :identify_card,label:"身份证号" %>
          </div>

          <div class="field">
            <%= user_f.input :email ,label:"Email"%>
          </div>

          <div class="field">
            <%= user_f.input :tinypost_number ,label:"微信"%>
          </div>

          <div class="field">
            <%= user_f.input :qq_number ,label:"QQ"%>
          </div>


    <% end %>




    <div class="form-actions">
      <%= f.button :submit ,'保存',inner_html: {class:"btn btn-primary"} %>

    </div>
<% end %>
    </div>
  </div>
</div>

app/views/teachers/edit.html.erb
<div class="page-content page-thin">
    <%= render partial:'shared/page_title_caption',object:'修改讲师' %>
    <%= render 'form' %>
</div>

app/views/teachers/index.html.erb
<div class="page-content page-thin">


  <%= render partial:'shared/page_title_caption',object: '讲师列表' %>

  <h3>共有讲师 <%= @teachers.length %> 人</h3>

<table class="ui padded table segment">
  <thead>
    <tr>

      <th>姓名</th>

      <th>身份证号</th>
      <th>手机号</th>
      <th>QQ</th>
      <th>微信</th>
      <th>电子邮箱</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>

        <td><%= teacher.name %></td>
        <td><%= teacher.user.try(:identify_card)  %></td>
        <td><%= teacher.user.try(:phone_number)  %></td>
        <td><%= teacher.user.try(:qq_number) %></td>
        <td><%= teacher.user.try(:tinypost_number)  %></td>
        <td><%= teacher.user.try(:email)   %></td>

        <%if current_user.can_manage_basic_data?%>
        <td>
          <%= link_to '修改', edit_teacher_path(teacher) ,{class:"btn btn-primary"}%>
          <%= link_to '设置密码', set_password_user_path(teacher.user), {class:"btn btn-primary"}%>
            <%if teacher.freezing_flag%>
                <%= link_to '解冻', unfreezing_teacher_path(teacher),{class:"btn btn-primary", method: :patch }%>
            <%else%>
                <%= link_to '冻结', freezing_teacher_path(teacher),{class:"btn btn-primary", method: :patch }%>
            <%end%>
            <%= link_to '删除', teacher, {class:"btn btn-danger",method: :delete, data: { confirm: '确认删除讲师?' }} %>
            </td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%if current_user.can_manage_basic_data?%>
<%= link_to '新建 讲师', new_teacher_path ,{class:"btn btn-primary"}%>
<%end%>

</div>

app/views/teachers/new.html.erb
<div class="page-content page-thin">
  <%= render partial:'shared/page_title_caption',object:'创建讲师' %>
  <%= render 'form' %>
</div>

app/views/teachers/show.html.erb
<h1></h1>
<div class="ui horizontal label"><h2> 讲师信息</h2></div>
<div class="ui segment">
<p id="notice"><%= notice %></p>


<p>
  <strong>名字:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>手机:</strong>
  <%= @teacher.user.phone_number %>
</p>


</div>

<% if current_user.can_set_teacher_info?(@teacher) %>
    <%= link_to '修改信息', edit_teacher_path(@teacher), {class: 'ui blue button'}%>
    <%= link_to '设置密码', set_password_user_path(@teacher.user), {class: 'ui blue button'}%>
<% end %>


<% if  current_user.employee? %>
    <%= link_to '返回到讲师列表', teachers_path ,{class: 'ui blue button'}%>
<% end %>